---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: geth
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
    image:
      repository: ethereum/client-go
      tag: stable
    args:
      - "--sepolia"
      - "--syncmode=full"
      - "--gcmode=archive"
      - "--datadir=/root/.ethereum"
      - "--http"
      - "--http.api=eth,net,web3,engine"
      - "--http.addr=0.0.0.0"
      - "--http.port=8545"
      - "--http.corsdomain=*"
      - "--http.vhosts=*"
      - "--http.rpcprefix=/"
      - "--authrpc.addr=0.0.0.0"
      - "--authrpc.port=8551"
      - "--authrpc.vhosts=*"
      - "--ws"
      - "--ws.addr=0.0.0.0"
      - "--ws.port=8546"
      - "--ws.origins=*"
      - "--ws.api=eth,net,web3,engine"
      - "--ws.rpcprefix=/"
      - "--rpc.txfeecap=0"
      - "--rpc.gascap=0"
      - "--rpc.evmtimeout=10s"
    service:
      main:
        primary: true
        ports:
          http:
            primary: true
            port: 8545
          ws:
            primary: false
            port: 8546
          authrpc:
            primary: false
            port: 8551
      p2p:
        primary: false
        type: NodePort
        ports:
          protocol:
            primary: false
            procotol: TCP
            targetPort: 30303 # port in container
            port: 30303
            nodePort: 30303
          discovery:
            primary: false
            procotol: UDP
            targetPort: 30303 # port in container
            port: 30304
            nodePort: 30304
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: video-input-antenna
        hosts:
          - host: &host "geth.${SECRET_DOMAIN}"
            paths:
              - path: /http
                pathType: Prefix
                service:
                  port: 8545
              - path: /ws
                pathType: Prefix
                service:
                  port: 8546
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /mnt/data/ethereum/geth
        mountPath: /root/.ethereum
