apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:/Wi0xsqzPJE+Hm4=,iv:KUG2esvpMH+fjwQJCvTSugonnO96G4VQfUNGtHE7D6c=,tag:sGL3OBxcJ8hy/2qvK0A42A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:wXUfdtMDMxSByQ1UI5P/cNFEVc93QAOe,iv:K+2SsUXr/naEfnMj57XC9z1fOjSvm38ENjp1BljdJWg=,tag:pPmIVttuBIv3CxzNASG3Tw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:a9zfP22burxvpj887SqBc8ayfEJSpTN47uEevhUXw2JoMsI7,iv:2Um3Jg02Fua0Lt4trAO9JkhJDoACY+DaZvA985hm32M=,tag:JpjZRah72zLBXxrc8KZEew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ynzhn59vjy0tp87dnzjlxypukffskcga5dtgu3raz3r5jspja5fq99a8a8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPU1M4eXBWdDdTcEJXcXRE
            TkplQ2o3UEp5NnlCUHBnMjJIcHVNTW1WZFZjCmpWeWlSSlM0R3Bka1ZEeVZTbEJS
            Qzh2ckZlekc2S0gvc1RFTjZwc3pYZEEKLS0tIHZ4MmluMG1Xb0dHbDJqaFdNcDJU
            azhnV3c0OEVWaVBVWEk0OC9mZmQ4TmsKwQz6h59OiFDQ14gavoAPuQIof+AQoQI8
            WrCLP4KZ3tJjHRG0/Gf/Pn0L4YuOREoU4k6mqlKKYkZDOxbKyRyXBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-18T12:41:34Z"
    mac: ENC[AES256_GCM,data:Q6+HwI4EWi/ZWMqM8ktvxebgeJAqy186mtSzjLPvP0Lqm8jf2doUdsMOHdbvmYGAbolqc9STB0tfU7I1nTiS+JlM4g8u8tpu3TeYBe0Cma+Hitm7OolV0O4BQDcbH7jb67kv8CDmQ3bPsXvxy3NVKb9kVpDI1w5E2mRZqSpJ578=,iv:HQoOI+lxV1a0NeOeJZuXCmV3dIYBktl5dLN70IEdkdA=,tag:xPZSsHVhdasJILXxTAd9tg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
