---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-default-jellyfin-app
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/jellyfin/app
  prune: true
  dependsOn:
    - name: cluster-apps-nvidia-gpu-operator
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 5m
