---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repositories
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/flux/repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
