---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app unifi-controller
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      type: statefulset
    image:
      repository: lscr.io/linuxserver/unifi-controller
      tag: latest@sha256:d90337783b0e5cd23766a6bfaffb9a701138407044a607f236d49d4fd05e49e8
    env:
      TZ: Europe/Ljubljana
      PUID: 568
      PGID: 568
    service:
      main:
        primary: true
        ports:
          http:
            primary: true
            port: &port 8443
      other:
        primary: false
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: 192.168.30.203
        externalTrafficPolicy: Local
        ports:
          device:
            primary: false
            port: 8080 # service port
            targetPort: 8080 # container port
            nodePort: 8080
            protocol: TCP
          discovery:
            primary: false
            port: 10001
            targetPort: 10001
            nodePort: 10001
            protocol: UDP
          disocvery-l2:
            primary: false
            port: 1900
            targetPort: 1900
            nodePort: 1900
            protocol: UDP
          stun:
            primary: false
            port: 3478
            targetPort: 3478
            nodePort: 3478
            protocol: UDP
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:router-wireless
          hajimari.io/enable: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: &host "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
        - 568
    persistence:
      config:
        enabled: true
        type: hostPath
        mountPath: /config
        hostPath: /mnt/data/unifi-controller/config
    resources:
      requests:
        cpu: 10m
        memory: 200Mi
      limits:
        memory: 2000Mi
