apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:1Emev9zc/f5otyZemh8lvFJngS9Uhow+meWEGBEIzFQuVIrA,iv:knPnJ+Qq3RgjIimIV23HwgA6zMlysVXgxLUS9xKFcJw=,tag:8bgHnR6Jfe5lJUzpPafJ5g==,type:str]
    credentials.json: ENC[AES256_GCM,data:jDtFOJM9zuBCk8XoRxzkJnR+mvo/ILmkJHefnOGXXoPrruGzctWVLHP70wnaylGlTV2AFO9cGAlrtHqfCE6iiPI7y34GAYZIIg+4F49Ymx2Ucz1AA3i+q1/Rzi5ezHn2L/o++V3voX5o79ZjOJ77WYq9/AKdkeH9ggFAqc2wf/XLc/OEzClKcyREdkz0bhC8aJEwpEEGFW/u+WM84cvhFQ1KMqIisHVg/+t/v/S6TQ==,iv:JCSvGIeHF0e6qaKPHKCEVRpyzjH0D1hlU+vh48qAS10=,tag:O3wzYdgIfN9iEO4UyQc8OA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ynzhn59vjy0tp87dnzjlxypukffskcga5dtgu3raz3r5jspja5fq99a8a8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VjZ3NGU5eTYwb2hYOUw3
            YWhkM2kzL29QWEFOYUVudFhMa2ZyZDFjbFZZCnJZbUNjOGNtNjVmVk5DOWhCcTRM
            VzQ5Q1dRVXdmajBhM2s1aWZmbEZuMlkKLS0tIG1WaEZ1c2VUSTYvZmppTzdUdnhG
            UzcxQjJrNEVLcmFZQjUzM0xnb3c2RlkKayAKO/U0UvEJc/IV9KDbhafPYQ1ZHRt+
            3Lupg3YAMZK6y27mS2WT04Bhtdi7thDgBeFmGNl9uYRAo3NQirhl7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-18T12:41:34Z"
    mac: ENC[AES256_GCM,data:m8+Y/2bJp49HGSWT9WiqRZnm6m9qZ06sCJpA7wHwpN/sjLBdX/MuG44HWtZs5YbHjFjXql2IKoedO70CS8BOnUFvj0PurHL4WQ+l6JOrEpiZoNUehJCzp4Wl9pqDis66LE3wujro959pvnIPn/G0h16imC5HFOLiy7VJIYti3U0=,iv:gYj149Jnv9QCDFzGUEezc9aEq3HyMv1IoXCG8px4j+E=,tag:cKwRs0T9d6Snq67OF9eztQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
