---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - cert-manager
  - flux-system
  - kube-system
  - monitoring
  - networking
  - system-upgrade
  - gpu-operator
